# -*- coding: utf-8 -*-
"""Employee_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12kDXpDZYrQbmLg7vhdaLL-7Kai-w4k4Y
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

#1.
# Explore the data and load it into a Pandas DataFrame.
File=pd.read_excel('/content/Employee Sample Data - A.xlsx')
df=pd.DataFrame(File)
print(df.to_string())

#2.
# Clean the data.
#Befor clreaning the data we have to know the information about the data
df.info()
df.duplicated()
# Droped the last col because it has alot of null values
df=df.drop('Exit Date',axis=1)
# Then Drop the null value from the rest col
df.dropna(inplace=True)


#3.
# Modify the first 5 rows (input any values).
for x in df.head().index:
  for j in df.head().columns:
    df.loc[x,j]=input(f'inter a new value in row {x} column {j}  ')
#to show the results from 3
df.head()


#4.
# Print the row with the largest salary.
max=df.loc[df['Annual Salary'].idxmax()]


#5.
# Group the data by department and calculate both the average age and the average salary.
df.groupby('Department')[['Age','Annual Salary']].mean()

#6.
# Group the data by department+ethnicity, then find the maximum age ,
# minimum age, and median salary.
df.groupby(['Department','Ethnicity']).agg({
    'Age':['max','min'],
    'Annual Salary':'median'
})

# 7.
# Save your work in a new Excel file.
with pd.ExcelWriter('/content/Employee Sample Data - A.xlsx') as writer:
  df.to_excel(writer,sheet_name='Employee Sample Data New',index=False)


#Graphs

#Department distribution
df['Department'].value_counts().abs().plot(kind='bar')
font_title={'family':'serif','color':'green','size':20}
font_label={'family':'serif','color':'orange','size':20}
plt.title('Department Distribution',fontdict=font_title)
plt.xlabel('Department',fontdict=font_label)
plt.ylabel('count ',fontdict=font_label)
plt.show()

#Age Distribution
plt.hist(df['Age'],bins=10,edgecolor='black')
font_title={'family':'serif','color':'green','size':20}
font_label={'family':'serif','color':'orange','size':15}
plt.title('Age Distribution',fontdict=font_title)
plt.xlabel('Age',fontdict=font_label)
plt.ylabel("Number of Employees",fontdict=font_label)
plt.show()

#Salary by Department
plt.figure(figsize=(10,5))
sns.boxplot(x='Department', y='Annual Salary', data=df)
plt.xticks(rotation=45)
plt.title("Salary Distribution by Department",font_title)
plt.show()

#Gender Distribution
plt.figure(figsize=(10,5))
plt.pie(df['Gender'].value_counts(),labels=df['Gender'].value_counts().index,autopct='%1.1f%%')
plt.title("Gender Distribution",font_title)
plt.show()
plt

#Age vs Salary
plt.scatter(df['Age'],df['Annual Salary'])
plt.title("Age vs Salary",font_title)
plt.xlabel('Age',fontdict=font_label)
plt.ylabel('Annual Salary',fontdict=font_label)

#Bouns vs salary
plt.scatter(df['Bonus %'],df['Annual Salary'])
plt.title("Bouns vs salary",font_title)
plt.xlabel('Bouns %',fontdict=font_label)
plt.ylabel('Annual Salary',fontdict=font_label)
plt.show()

# Employee by country
plt.figure(figsize=(10,5))
sns.countplot(x='Country',data=df)
plt.title("Employee by conutry",font_title)
plt.show()
  df.to_excel(writer,sheet_name='Employee Sample Data New',index=False)
